name: Deploy MDXpress Docs to GitHub Pages

description: >
  Build the MDXpress documentation app in apps/docs and deploy the dist folder to GitHub Pages.

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: apps/docs/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies (docs)
        working-directory: apps/docs
        run: npm install

      - name: Build docs app
        working-directory: apps/docs
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create 404.html for docs SPA routing
        working-directory: apps/docs/dist
        run: cp index.html 404.html

      - name: Install dependencies (amelcraft)
        working-directory: apps/amelcraft
        run: npm install

      - name: Build amelcraft app
        working-directory: apps/amelcraft
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create 404.html for amelcraft SPA routing
        working-directory: apps/amelcraft/dist
        run: cp index.html 404.html

      - name: Prepare site directory
        run: |
          mkdir -p site/docs
          mkdir -p site/amelcraft
          cp -r apps/docs/dist/* site/docs/
          cp -r apps/amelcraft/dist/* site/amelcraft/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
